In [1]:
import numpy as np

class Image:
    def __init__(self, mask):
        self.mask = mask

    def move_submatrix(self, shift, selected_area):
        shift_y, shift_x = shift
        x1, y1, x2, y2 = selected_area
        result = self.copy()
        matrix = self.mask
        
        # Create a new submatrix with zeros
        submatrix = matrix[y1:y2, x1:x2]
        shifted_submatrix = np.zeros_like(submatrix)
        
        # Calculate the ranges for the new submatrix
        start_x = max(0, shift_x)
        end_x = submatrix.shape[1] - max(0, -shift_x)
        start_y = max(0, shift_y)
        end_y = submatrix.shape[0] - max(0, -shift_y)
        
        # Calculate the ranges for the old submatrix
        old_start_x = max(0, -shift_x)
        old_end_x = submatrix.shape[1] - max(0, shift_x)
        old_start_y = max(0, -shift_y)
        old_end_y = submatrix.shape[0] - max(0, shift_y)
        
        # Copy the values to the new submatrix
        shifted_submatrix[start_y:end_y, start_x:end_x] = submatrix[old_start_y:old_end_y, old_start_x:old_end_x]
        
        # Zero out the original submatrix positions in the result matrix
        result.mask[y1:y2, x1:x2] = 0
        
        # Place the shifted submatrix back into the result matrix
        result.mask[y1:y2, x1:x2] = shifted_submatrix
        
        return result
    
    def copy(self):
        return Image(self.mask.copy())

# Example usage
matrix = np.array([
    [0, 0, 0, 0, 0, 0, 0, 0, 0],
    [0, 2, 0, 0, 0, 0, 0, 0, 0],
    [0, 2, 0, 2, 0, 0, 0, 0, 0],
    [0, 2, 0, 2, 0, 2, 0, 0, 0],
    [0, 2, 0, 2, 0, 2, 0, 2, 0],
    [0, 2, 0, 2, 0, 2, 0, 2, 0],
    [0, 2, 0, 2, 0, 2, 0, 2, 0]
])

image = Image(matrix)
shift = (1, 1)
selected_area = (1, 1, 6, 6)

result = image.move_submatrix(shift, selected_area)
print(result.mask)


[[0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0]
 [0 0 2 0 0 0 0 0 0]
 [0 0 2 0 2 0 0 0 0]
 [0 0 2 0 2 0 0 2 0]
 [0 0 2 0 2 0 0 2 0]
 [0 2 0 2 0 2 0 2 0]]
